name: Swift

on: [push]

jobs:
  macOS:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macOS-14
        swift-version:
          - '5.9'
        swift-compat-ver:
          - '5'
          - '4.2'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test for macOS
      run: swift build
            